name       : tagainijisho
version    : 1.1.92
release    : 2
source     :
    - https://github.com/Gnurou/tagainijisho/releases/download/1.1.92/tagainijisho-1.1.92.tar.gz : 2e66ea9f7cf1902f5edcf8545245bf622f378a7878f2d181c7b5c528a1e7f5bb
homepage   : https://www.tagaini.net/
license    : GPL-3.0-or-later
component  : office
summary    : A free Japanese dictionary and learning assistant
description: |
    Tagaini Jisho is designed to help you remember Japanese vocabulary and kanji (later referred as 'entries') by presenting them in a way that makes it easy to create connections between them. It does so by keeping track of all the entries you already know and want to study, and letting you tag and annote them, in addition to providing easy navigation between related entries. A powerful search engine also allows you to search for entries very precisely. Finally, Tagaini let you produce printed material (including a handy foldable pocket book) so let you study anywhere.
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
