name       : tagainijisho
version    : 1.1.94
release    : 4
source     :
    - https://github.com/Gnurou/tagainijisho/releases/download/1.1.94/tagainijisho-1.1.94.tar.gz : 47ebc617557ceaba4bb9a50fd96ace363f7e8291a72d7d7042e3104fcfb8cfe2
homepage   : https://www.tagaini.net/
license    : GPL-3.0-or-later
component  : office
summary    : A free Japanese dictionary and learning assistant
description: |
    Tagaini Jisho is designed to help you remember Japanese vocabulary and kanji (later referred as 'entries') by presenting them in a way that makes it easy to create connections between them. It does so by keeping track of all the entries you already know and want to study, and letting you tag and annote them, in addition to providing easy navigation between related entries. A powerful search engine also allows you to search for entries very precisely. Finally, Tagaini let you produce printed material (including a handy foldable pocket book) so let you study anywhere.
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
