name       : tagainijisho
version    : 1.0.3
release    : 1
source     :
    - https://github.com/Gnurou/tagainijisho/releases/download/1.0.3/tagainijisho-1.0.3.tar.gz : 6fe3c579ec1cea6c41393ac9a82dd12d0e240032d2bb7837a90e470f480aaf4e
license    : GPL-3.0
component  : office
summary    : A free Japanese dictionary and learning assistant
description: |
    Tagaini Jisho is designed to help you remember Japanese vocabulary and kanji (later referred as 'entries') by presenting them in a way that makes it easy to create connections between them. It does so by keeping track of all the entries you already know and want to study, and letting you tag and annote them, in addition to providing easy navigation between related entries. A powerful search engine also allows you to search for entries very precisely. Finally, Tagaini let you produce printed material (including a handy foldable pocket book) so let you study anywhere.
builddeps  : 
    - pkgconfig(QtCore)
setup      : |
    %cmake -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
       -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
       -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
       .
build      : |
    %make
install    : |
    %make_install
